name: WaterWalking
version: ${project.version}
main: me.adelemphii.waterwalking.WaterWalking
author: Adelemphii
api-version: 1.13

commands:
  togglewaterwalking:
    aliases: toggleww
    description: Toggles waterwalking
  settings:
    description: Opens the GUI for settings!